---
- name: Job Template 0 - Altyapı ve Bağımlılıkların Kurulumu
  hosts: hedef_sunucular
  become: yes
  gather_facts: yes
  tasks:
    # ==========================================
    # DEBIAN & UBUNTU AİLESİ
    # ==========================================
    - name: (Debian/Ubuntu) Temel bağımlılıkları ve OpenSCAP'i kur
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg
          - jq
          - needrestart
          - "libopenscap*" # Trivy yerine OpenSCAP'in doğru sürümünü otomatik kurar
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    # ==========================================
    # REDHAT, CENTOS & ROCKY AİLESİ
    # ==========================================
    - name: (RedHat/CentOS) Temel bağımlılıkları ve OpenSCAP'i kur
      yum:
        name:
          - wget
          - jq
          - yum-utils
          - openscap-scanner # RedHat tabanlı sistemler için OpenSCAP paketi
        state: present
      when: ansible_os_family == "RedHat"