---
- name: Job Template 1 - Zafiyet Taramasi ve Konsol Raporu
  hosts: hedef_sunucular
  become: yes
  tasks:
    - name: Trivy ile sunucuyu tara (Sadece yamasi olanlari tablo yap)
      command: trivy fs / --scanners vuln --ignore-unfixed
      register: trivy_sonucu
      ignore_errors: yes

    - name: Zafiyet Tablosunu AWX Ekranina Bas
      debug:
        msg: "{{ trivy_sonucu.stdout_lines }}"