---
- name: OpenSCAP Akıllı Zafiyet Taraması ve Nginx Raporlama
  hosts: hedef_sunucular
  become: yes
  tasks:
    - name: OpenSCAP aracını sunucuya kur
      apt:
        name: libopenscap8
        state: present

    - name: Ubuntu'nun günlük resmi OVAL (Zafiyet Veritabanı) dosyasını indir
      get_url:
        url: "https://security-metadata.canonical.com/oval/com.ubuntu.{{ ansible_distribution_release }}.cve.oval.xml"
        dest: /tmp/ubuntu_cve.xml

    - name: Canlı sistemi tara ve HTML rapor oluştur (Sadece aktif çalışanlar)
      shell: oscap oval eval --report /tmp/{{ inventory_hostname }}_scap_raporu.html /tmp/ubuntu_cve.xml
      ignore_errors: yes # OpenSCAP açık bulduğunda hata kodu döner, süreci kesmemesi için ekliyoruz

    - name: Raporu AWX üzerinden Nginx yayın dizinine fırlat
      copy:
        src: /tmp/{{ inventory_hostname }}_scap_raporu.html
        dest: /var/www/html/raporlar/{{ inventory_hostname }}_scap_raporu.html
      delegate_to: 172.30.11.11
      become: no